#!/bin/sh

usage () {
    echo "Usage: $0 [-o outputdir] input [input2] [inputN]" 1>&2
    exit 1
}

while getopts ":o:" opt; do
    case $opt in
        o)
            output_dir=${OPTARG}
            ;;
        \?)
            usage
            ;;
    esac
done

function main () {
    if [ -n "$output_dir" ]; then
        if [ ${#@} -gt 0 ]; then
            process_input $@
        else
            # no arguments to script
            echo "input must be provided"
            exit
        fi
    else
        echo "output directory must be provided"
        exit 1
    fi
}

tmp_output_dir=tmp
style=xslt/headerdoc2html5.xslt

# validate params

function process_input() {
    echo $output_dir
    echo $tmp_output_dir
    shift 2
    echo $@

    # run headerdoc
    headerdoc2html -X -o $tmp_output_dir $@

    # then process $tmp_output_dir with xsltproc
    for dir in `find ${tmp_output_dir} -depth 1 -type d`; do
        echo "${dir}"
        for xmldoc in "${dir}/*.xml"; do
            echo $xmldoc
            docdir="$(dirname ${xmldoc})"
            docdir="${output_dir}${docdir#tmp}"
            htmldoc="$(basename ${xmldoc} .xml).html"

            mkdir -p "${docdir}"
            xsltproc --nonet -o "${docdir}/${htmldoc}" "${style}" $xmldoc
        done
        echo ""
    done
}

main $@
